---
    - name: "Download Kibana's rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
      register: download_kibana
      until: download_kibana is succeeded
    - name: Install Kibana
      become: true
      yum:
        name: "/tmp/kibana-{{ elk_stack_version }}-x86_64.rpm"
        state: present
    - name: chown
      become: true
      file:
        path: /usr/share/kibana
        owner: kibana
        group: kibana
    - name: Configure Kibana
      become: true
      template:
        src: kibana-config.yml.j2
        dest: /etc/kibana/kibana.yml
      notify: start Kibana
