---
- include_tasks: "download_{{ ansible_facts.pkg_mgr }}.yml"
- include_tasks: "install_{{ ansible_facts.pkg_mgr }}.yml"
- name: chown
  become: true
  file:
    path: /usr/share/kibana
    owner: kibana
    group: kibana
- name: Configure Kibana in SSH session
  become: true
  template:
    src: kibana-config.yml.j2
    dest: /etc/kibana/kibana.yml
  notify: restart Kibana
  when: ansible_virtualization_type != 'docker'
- name: Configure Kibana in Docker
  become: true
  template:
    src: kibana-config.yml.j2
    dest: /etc/kibana/kibana.yml
  when: ansible_virtualization_type == 'docker'
- name: Start Kibana in Docker
  shell: "(/usr/share/kibana/bin/kibana --allow-root >/dev/null 2>&1 &)" 
  async: 10
  poll: 0
  changed_when: false
  when: ansible_virtualization_type == 'docker'
