---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
#  - name: centos8
#    image: docker.io/pycontribs/centos:8
#    pre_build_image: true
#    exposed_ports:
#      - 5601/tcp
#    published_ports:
#      - 0.0.0.0:5601:5601/tcp
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
    published_ports:
      - 0.0.0.0:5601:5601/tcp
provisioner:
  name: ansible
verifier:
  name: ansible
